language: node_js
node_js: 9
cache:
  yarn: true
  directories:
  - frontend/node_modules
install:
- cd frontend/
- yarn install
- cd ../
script:
- cd frontend/
- yarn lint
- yarn build
- cd ../
before_deploy:
- deploy/travis_before_deploy.sh
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: ap-northeast-2
  bucket: samnote-deploy
  skip_cleanup: true
  upload-dir: main
  local-dir: tmp-upload
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: ap-northeast-2
  bucket: samnote-deploy
  key: main/$TRAVIS_COMMIT.zip
  application: samnote
  deployment_group: master
notifications:
  email: false
