language: node_js
node_js: 9
cache:
  yarn: true
  directories:
  - frontend/node_modules
install:
- cd frontend/
- yarn install
- cd ../
script:
- cd frontend/
- yarn lint
- yarn build
- cd ../
before_deploy:
- deploy/before.sh
deploy:
  provider: s3
  access_key_id:
    secure: FnDRl8Tk8elaMkJfpROfHnKjCJnPW+7jLxi+d52yqNvP+v8EPqYfJfGR83qVNDxaCww/obqbc640DILYPkaBoH6TRVdqA38x+Qgf4BWQZCZ3iGUIBxjufVB5tab8wdBBTMde/SU2TPI/KOKU1vA/pGcy67PesDioevENUlw+tzkp243IDS36mRTzrIweUAMe/vXDsi7mJk9xDgYULNJA2W4yGZ5gc4PaYcQ2hS5xv8D4AxVUGxPmLaxksDWxnyF2D0X5GIjB+3kKZhJuFelBYTYq4cB3G5ooqfgQjeZlRs5Gyp3JP1qD0rNFw1FuzxoZ6uuIOSpaZ+Q98NKKqjtvl9ePHOhCSeBI4okg2p8J8k3yFKCbrtcob96kEHzcUlhF1NfEmuMdj5G1cqXNCu+CC9BVqze2q1wwmjoB7rgAe0hfDcaZjSx9vxh5fyKwDy9xDdSKfFlktkuJnPjMEEQfc/c4mG+vBkUXYECyeg4VlG0KLMkjds/VCPptYyvlrbXkip1nS1z23TlwPcoZAqMvMdlueE90AiBlvYQ3ZrmYknzRllgJJtxUgw2hiAy//v6EqVuLQNPU7sALFNCnhqsWKefcq04Rt+M+7ys1DbEhG21NNymqoqayDQw+QSTpB3aM1sfuNF5RkbUjyBc1X9tWFPCijjkZnk5/+G0uIDcjvBg=
  secret_access_key:
    secure: KYEQy7+alzpQmiVfMpvgJbJK1JCxSgAgET93vow5if0Vmt0su3kd/f/FgJkaPLJ7ptmJxinMmRJsBcG1o1S5aoTDRdYjQ00EoboqzDESMsO7D0Dh1E2B/JTa8k6k8c4WXN7VuxXBMXUh4Tbxrc30liZ0ec2+DqixNVn0lPV5vXoZKQVfEy3kuZNjpr9tK5J559yBaLQwY9p/O82ODPzaYCXWM0OMWw2zolDSHM26xP/VY3FyN7BXKTrbpb3XB1EAMLoM/jgjo8NOBWuM77UpTzvbJTuY5VKyFGZLEgzijkPie+N4mhGvY2a4tUvYrb4RCNFxkBV56HGe/y4AXt34/fM/bX2WFY7smMVA2F0tq/n7Mzqx4i6jmW+pFY5IV+6qUlqt41sBJh4fMcQUreReuhmS1PydIT3/hYd12QwQLBW4c0VgGDvfOtjOjxZKJM8SKeHCWIKqGCHG+Cc5jMrHL7Arf+9Lc9U+IB8VnjbtiEvhRH5L2zdGePJNbK28I8qI/SNGG50RlbvFdu955bZfeYmmLZBzyQ2JBO97IDEEfSYAye59jrGktXJ6svZnbKr6l1s1brtAqWF9vy2Jhx0l0NaTQ+MYtc8Yoo6PRjIDYIMU8emRIDUTaAfmqO04B1lJ2QrEqdWSEN3bCLC8tNOgeDf9sYZ5ZbDKpdlC4XvfwVs=
  region: ap-northeast-2
  bucket: samnote-deploy
  skip_cleanup: true
  upload-dir: main
  local-dir: tmp-deploy
